import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import PageHeader from '../components/pageHeader'
import About from '../components/about'
import {motion} from 'framer-motion'
const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className={styles.main}>
         <PageHeader/>
          <About/>
      </main>

     
    </div>
  )
}

export default Home
